---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - vendor/**/*
    - lib/cpf_cnpj/version.rb
    - cpf_cnpj.gemspec

Style/OptionalBooleanParameter:
  Enabled: false
